import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { ToastContainer, toast } from "react-toastify";
import Header from "./components/header";
import Footer from "./components/footer";
import ScrollToTop from "./components/scrollToTop";
import NextTopLoader from "nextjs-toploader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="overscroll-y-none scroll-m-5">
        <NextTopLoader
          color="#000000"
          shadow="0 0 10px #2299DD,0 0 5px #2299DD"
          // showSpinner={true}
        />
        <Header />
        {children}
        <Footer />
        <ToastContainer
          position="top-right"
          autoClose={2000}
          hideProgressBar={false}
          newestOnTop
          closeOnClick={false}
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="colored"
        />
        <ScrollToTop />
      </body>
    </html>
  );
}
